on:
  pull_request:
    branches: [ "main" ]

jobs:
  runs-on: ubuntu-latest
  container: maven:4.0.0-rc-5-eclipse-temurin-25-noble
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: build project
      run: mvn clean package -DskipTests
